# Generated by Django 5.2.6 on 2025-09-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата в Telegram для отправки уведомлений', max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
